name: Python CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install pipenv
        run: pip install pipenv

      - name: Check Python version
        run: |
          python --version
          where python

      - name: Install dependencies with pipenv
        run: pipenv install  # This installs both default and dev dependencies

      - name: Run tests
        run: pipenv run pytest  # Replace with your test command
